# Generated by Django 4.2 on 2023-04-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
                ('release_date', models.DateField(max_length=10)),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
